### ISSUE TITLE
Restarting user plugins throws an error

### ISSUE THREAD

**Issue by casperc** [laurentpetit/ccw-plugin-manager#1]
Restarting the user plugins (Alt+U S) throws an exception that has no message:

![screen shot 2015-03-27 at 10 21 46](https://cloud.githubusercontent.com/assets/539481/6865130/1217f5e2-d46b-11e4-8ac5-365714b7918c.png)

But removing the getMessage on the exception shows the following:

![screen shot 2015-03-27 at 10 17 12](https://cloud.githubusercontent.com/assets/539481/6865080/6fc1893e-d46a-11e4-81cb-9371aa47bb46.png)

I have tested this on two different OSX machines, which both give the same result.

Edit:

Here is the stack trace, I don't know how where the log is printed to from the embedded repl, so the best option I have at the moment is a dialog:

![screen shot 2015-03-27 at 10 33 50](https://cloud.githubusercontent.com/assets/539481/6865351/26107f68-d46d-11e4-8f57-7f58a0e97e9e.png)

**Comment by laurentpetit** [comment]
Hello, What's the precise version of Eclipse you're using, and what are the user plugins that are installed in your `~/.ccw/` folder ?

**Comment by casperc** [comment]
I am using 0.31.1 standalone and I only have ccw-plugin-manager installed currently.

**Comment by laurentpetit** [comment]
Great, I can reproduce the error also! ;)

**Comment by laurentpetit** [comment]
The fix will be available in the next release of CCW. In the meantime, it is very easy to fix manually: you need to find the `user_plugins.clj` file in the standalone CCW installation folder, and add a (doall ) call around `to-remove` in line 51 (see the commit above for more detail)

**Comment by casperc** [comment]
Lovely
